name: Hello Workflow

on: push

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: |
         echo "Hello from GitHub Actions"
         pwd
         hostname
         ls -ltr
