name: Python Quality Check

on: push

jobs:
  test-and-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Pytest
        run: pip install pytest

      - name: Run Tests
        run: pytest test_app.py

      - name: Run Application
        run: python app.py
